
import agrismartapp.CropHistory;
import agrismartapp.CropRecommendations;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Filemanu = new javax.swing.JMenu();
        Exit = new javax.swing.JMenuItem();
        ViewMenu = new javax.swing.JMenu();
        CropRecommendation = new javax.swing.JMenuItem();
        SoilMoistureMonitoring = new javax.swing.JMenuItem();
        CropHistory = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Filemanu.setText("File");

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        Filemanu.add(Exit);

        jMenuBar1.add(Filemanu);

        ViewMenu.setText("View");

        CropRecommendation.setText("CropRecommendation");
        CropRecommendation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CropRecommendationActionPerformed(evt);
            }
        });
        ViewMenu.add(CropRecommendation);

        SoilMoistureMonitoring.setText("Soil Moisture Monitoring");
        SoilMoistureMonitoring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoilMoistureMonitoringActionPerformed(evt);
            }
        });
        ViewMenu.add(SoilMoistureMonitoring);

        CropHistory.setText("Crop History");
        CropHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CropHistoryActionPerformed(evt);
            }
        });
        ViewMenu.add(CropHistory);

        jMenuBar1.add(ViewMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ExitActionPerformed

    private void CropRecommendationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CropRecommendationActionPerformed
        // TODO add your handling code here:
        CropRecommendations recomand= new CropRecommendations();
        recomand.show();

        
    }//GEN-LAST:event_CropRecommendationActionPerformed

    private void CropHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CropHistoryActionPerformed
        // TODO add your handling code here:
        CropHistory crop = new CropHistory();
        crop.show();
    }//GEN-LAST:event_CropHistoryActionPerformed

    private void SoilMoistureMonitoringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoilMoistureMonitoringActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SoilMoistureMonitoringActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CropHistory;
    private javax.swing.JMenuItem CropRecommendation;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu Filemanu;
    private javax.swing.JMenuItem SoilMoistureMonitoring;
    private javax.swing.JMenu ViewMenu;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
